### ISSUE TITLE
Updates from 8/6/22

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeOnto#14]
Dataset has ‘number of features’ and ‘number of instances’
'has goal' some 'AI Task Goal'
AIModel ‘annotates’/‘annotatedby’ AIModelAssessmentResult
![Screenshot 2022-06-08 at 12 33 40](https://user-images.githubusercontent.com/233262/172606633-20324e60-1fbc-4aaf-85f9-44c2aba48f23.png)

Retrieval is a rule for  
1. Number of instances
2. Number of features 

A new class for "Restriction" 
- has comparator
- Has a relationship
- Is on the path from T

**Comment by ike01** [comment]
@anjanaw  is that not `AI Task` _realizes_ some `AI Task Goal` or are you proposing to make it `Dataset` _has goal_ some `AI Task Goal`?

**Comment by anjanaw** [comment]
I dont remember what any of these means, it's opened in June. most of it must be already done. 
i think these individually asks for new concepts/predicates. 
1. Dataset has ‘number of features’ and ‘number of instances’ (done)
2. 'has goal' some 'AI Task Goal' (not sure)
3. AIModel ‘annotates’/‘annotatedby’ AIModelAssessmentResult (not sure)

**Comment by dcorsar** [comment]
1.     Dataset has ‘number of features’ and ‘number of instances’ (done)
2.     'has goal' some 'AI Task Goal' (not sure). Is this Dataset hasGoal some Goal? Does it make sense for a Dataset to have a Goal? What type of Goal would it be?
3.     AIModel ‘annotates’/‘annotatedby’ AIModelAssessmentResult (should be done)

**Comment by anjanaw** [comment]
"User Group"-->"hasKnowledgeOfDomain" --> "Domain" i think this is missing as well.

**Comment by anjanaw** [comment]
"User Group" --> 'has goal' --> 'SIO_000006' is there. not sure what it has to do with AI Task Goal and if we still need this

**Comment by anjanaw** [comment]
> 3. ```
>    AIModel ‘annotates’/‘annotatedby’ AIModelAssessmentResult (should be done)
>    ```
can you pls confirm?

**Comment by anjanaw** [comment]
any updates? @dcorsar @ike01

**Comment by anjanaw** [comment]
@dcorsar 
1. iSeeOnto has the following

> AIModelAssessmentResult annotates AIModel 
> annotatedBy is the reverse of annotates

Does this mean, there is no need to explicitly say "AIModel annotatedBy AIModelAssessmentResult"?

2. Cannot find "User/UserGroup _hasKnowledgeOfDomain_ Domain" Domain is not linked to any other Concept either.

**Comment by dcorsar** [comment]
> @dcorsar
> 
>     1. iSeeOnto has the following
> 
> 
> > AIModelAssessmentResult annotates AIModel
> > annotatedBy is the reverse of annotates
> 
> Does this mean, there is no need to explicitly say "AIModel annotatedBy AIModelAssessmentResult"?

Yes - it would be inferred by a reasoner, so no need to explicitly add it

> 
>     2. Cannot find "User/UserGroup _hasKnowledgeOfDomain_ Domain" Domain is not linked to any other Concept either.

How it would have been done is 'User' 'possess' 'Domain Knowledge' 'in relation to' 'Domain'
This is a bit long winded, so have added a 'possessKnowledgeOf' property as a subproperty of 'possess' and and a constraint that 'User' 'possessKnowledgeOf' 'Domain' to user.rdf
