### ISSUE TITLE
Outcome 

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeOnto#17]
1. add "Outcome" "isBasedOn" "Metric"
2. Question subclasses with support to different response types
3. How does it affect the existing relationship "Outcome" "isDerivedFrom" "User Evaluation Result"

**Comment by anjanaw** [comment]
1. questionnaire on a real use case: https://cockpit-dev.isee4xai.com/ with login below you can find a use case named "telco recommender2" under each intent there is an evaluation questionnaire. These are not currently included in the case JSON export (which is what we are trying to fix)

2. more questionnaires from Hoffman paper are added here. https://cockpit-dev.isee4xai.com/questionnaires
if you use the export button u can see how they export to JSON now.

3. even more questionnaires can be found on the Hoffman paper itself. https://arxiv.org/pdf/1812.04608.pdf

4. 3 questionnaires for fake use cases here: https://www.overleaf.com/5198652528sckynmbcqzrr I made these up, but they given an idea of the complete case and where evaluation questionnaires sit.

**Comment by dcorsar** [comment]
How suitable is the Survey Ontology - https://cefriel.github.io/survey-ontology/docs/index.html for capturing the types of information required about questionnaires?

**Comment by anjanaw** [comment]
From #30 and discussions
1. UserEvaluationReponse will hold a response to a question from a user.  #30
2. Later we will determine how to aggregate and what concepts will link aggregated results to the case. 

I will leave this issue open for now.
