### ISSUE TITLE
User Group

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeOnto#18]
1. Should User Group be linked directly as a case feature?
2. update case_structure.json with User Group. 
3. update all seed cases with User Group.

**Comment by dcorsar** [comment]
> 1. Should User Group be linked directly as a case feature?

`User_Group` is a subclass of `user` so as `user` is already a subclass of `CaseFeature` so is `User_Group` - do we need to add anything else?

**Comment by anjanaw** [comment]
CaseFeature is representing how iSee defines a case. Therefore it can be confusing to leave it as User if a use case is created per User Group.

**Comment by dcorsar** [comment]
How would this confusion be resolved? Add more specificity to the case feature descriptions? Such as:

Remove `User` `subclassOf` `CaseFeature` and `Description` `hasUser` `User` assertions from explanationexperience.rdf and replace with
`User_Group` `subclassOf` `CaseFeature` and `Description` `hasUserGroup` `User_Group` assertions

**Comment by anjanaw** [comment]
Completed in https://github.com/isee4xai/iSeeOnto/pull/28
