### ISSUE TITLE
Number of features and Number of instances

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeOnto#21]
Convert to categorical. 

> Number of features

> Number of instances

for example, features <10, 10<100 and >100
get some feedback from Derek as to what categories are useful for similarity retrieval.

**Comment by dcorsar** [comment]
Added two properties: `featureCountRange` and `instanceCountRange` and a class `QuantityRange` in [https://github.com/isee4xai/iSeeOnto/pull/23](https://github.com/isee4xai/iSeeOnto/pull/23)

Going forward there are two options for definition different quantity ranges:
- individuals of `QuantityRange' where the definition of the range (e.g. number of features is less than 10) in the rdfs:comment or other documentation). This is the simplest and recommended for now if it satisfies the use case needs.
- define the ranges explicitly as different subclasses of `QuantityRange` - e.g. that LowFeatureRange is the class of all things that have numberOfFeatures less than 10.
