### ISSUE TITLE
User evaluation concept renaming

### ISSUE THREAD

**Issue by dcorsar** [isee4xai/iSeeOnto#30]
change 'UserEvaluationResult' to 'UserEvaluationResponse'
add relationship 'UserEvaluationResult' 'hasObjectValue' 'KeyLiteralValuePair'

**Comment by dcorsar** [comment]
@anjanaw done, and pushed to userevalatuion.rdf in https://github.com/isee4xai/iSeeOnto/tree/issue-20 please check then we can merge.
Had to rename `hasValue` to `hasObjectValue` to avoid naming clash.

**Comment by anjanaw** [comment]
Looks good. Merged to main.

**Comment by anjanaw** [comment]
@dcorsar Is a data property assertion suitable to store an answer to an open question? 
for now, I will use prov:value, if not suitable, needs to create a new data property assertion.

**Comment by dcorsar** [comment]
prov:value is fine for open questions. I've added a new class for Open Question Responses to differentiate them from nominal question responses.
