### ISSUE TITLE
base IRI for EE instances

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeOnto#32]
What is the best practice when selecting the base IRI for instance? 

For example, consider NetflixExplanationExperience, the AIModel instance would be NetflixAIModel. Which base IRI should the NetflixAIModel have? Is it 

1. http://www.w3id.org/iSeeOnto/explanationexperience# (meaning all instances in the NetflixExplanationExperience will have the same base IRI)
or 
2. http://www.w3id.org/iSeeOnto/aimodel#. (meaning instances in the NetflixExplanationExperience will inherit IRI from their class/type/concept)

**Comment by dcorsar** [comment]
I'd suggest using a base iri that's going to allow differentiations between use cases. For example

- http://www.w3id.org/iSeeOnto/explanationexperience/netflix/ for all netfix explanation experience concepts
- http://www.w3id.org/iSeeOnto/explanationexperience/use_case_x/ for all use_case_x explanation experience concepts

So we'd have something like
- http://www.w3id.org/iSeeOnto/explanationexperience/netflix/netflixAIModel
- http://www.w3id.org/iSeeOnto/explanationexperience/netflix/netflixDataset
- http://www.w3id.org/iSeeOnto/explanationexperience/netflix/netflixExplanationTechnique

That way we know everythign related to the an explaination experience will have that common base.  

If desired, it could be expanded further by type - for example, say there are two datasets
- http://www.w3id.org/iSeeOnto/explanationexperience/netflix/dataset/netflixDataset1
- http://www.w3id.org/iSeeOnto/explanationexperience/netflix/dataset/netflixDataset2
