### ISSUE TITLE
UserQuestionTarget subclasses

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeOnto#33]
currently has AIMethods and SystemRecommendation, should Dataset be one as well? 

<img width="243" alt="Screenshot 2022-11-24 at 19 35 37" src="https://user-images.githubusercontent.com/233262/203854863-8249ce52-b056-4018-a551-ce246867577d.png">

**Comment by anjanaw** [comment]
When creating an EE instance, 
- if AIMethod is the target, we can link the AIMethod instance they create for the EE
- if Dataset is the target, we can link the Dataset instance they create for the EE

what do we do when SystemRecommendation is selected? 
- create a fake instance with SystemRecommendation as the concept? 
or
- does this mean we should keep track of a list of possible System Recommendations in the case, maybe as part of the AIModel?

**Comment by dcorsar** [comment]
> currently has AIMethods and SystemRecommendation, should Dataset be one as well?
> 
> <img alt="Screenshot 2022-11-24 at 19 35 37" width="243" src="https://user-images.githubusercontent.com/233262/203854863-8249ce52-b056-4018-a551-ce246867577d.png">

Added

**Comment by dcorsar** [comment]
> 

The SystemRecommendation is the thing that the user has requested an explanation in relation to. We don't necessarily need to keep track of all of them, but will require an individual of type SystemRecommendation for the one that the user is asking about.  They are related to the AIModel, via the AIMethod. The AIModel utilises an AI Method which has output the System Recommendation.

**Comment by anjanaw** [comment]
@dcorsar 'individual of type SystemRecommendation' when/where/how is this individual created if not as part of the use case?

**Comment by dcorsar** [comment]
When would that information be available? For cases where we already know the thing we're explaining then it could be when everything else get created. in terms of what information goes into it - is that going to be use case specific? Perhaps we start with using an individual with a label describing the recommendation?

**Comment by anjanaw** [comment]
"AI Task" "has output" "System Recommendation"
@ike to investigate if "System Recommendation" needs subclasses for different AI tasks. for example, for  Classification vs Regression.

**Comment by dcorsar** [comment]
the 'AI Task' 'used' 'AI Method' and the 'AI Method' 'has output' 'System Recommendation'

'System Recommendation' 'was generated by' 'AI Task' - so the inverse is true that 'AI Task' 'generated' 'System Recommendation' 

Its straightforward enough to add subclasses of 'System Recommendation'  - this would be beneficial as it would allow a more accurate representation of the case to be defined. Shall we start with Classification and Prediction then extend as necessary as we proceed?
