### ISSUE TITLE
AIModelAssessmentResult 

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeOnto#34]
What is the composition of AIModelAssessmentResult? 

> AIModelAssessmentResult

> > prov:value: rdfs:Literal (is this the correct data property/data type?)

> > resultOf: AIModelAssessment (do we need this? for user evaluation it makes sense, but for this not so much) 

> > basedOn: AIModelAssessmentMetric (has instances)

> > measures: AIModelAssessmentDimension (has instances)

**Comment by dcorsar** [comment]
that all looks good.
AIModelAssessment is added for completeness in terms of provenance and usually to add the link 'AIModenAssessment' 'qual:assesses' 'AI Model' individual.
This could be replaced by adding 
'AIModelAssessmentResult'  'qual:annotates' 'AI Model'

**Comment by anjanaw** [comment]
@ike01 can you add these connections to the AIModelAssessmentResult, it currently only has 'qual:annotates' 'AI Model'. 
<img width="441" alt="Screenshot 2022-12-05 at 18 55 00" src="https://user-images.githubusercontent.com/233262/205720119-6f153f3d-e0b3-4ea9-87cc-96f92efc821a.png">

**Comment by dcorsar** [comment]
Added the restrictions above to the AI Model Assessment Result class in https://github.com/isee4xai/iSeeOnto/blob/issue-20/userevaluation.rdf

**Comment by anjanaw** [comment]
merged.
