### ISSUE TITLE
Intent instances

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeOnto#37]
Update intent instances to reflect the outcomes of D4.3. Intent individuals are 
- Debugging
- Comprehensibility
- Effectiveness
- Actionability
- Scrutability
- Transparency
- Performance
- Compliancy

**Comment by dcorsar** [comment]
@anjanaw have added these to the user.rdf on the main branch.  They just have labels for now - will need to check the deliverable to get definitions to add.
