### ISSUE TITLE
keeping track of AI Model URL and other meta info

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeOnto#38]
I need to keep track of AI Model file/URL and other meta info on the case structure, what predicate/concept can we use to do that? for now, it can be as simple as "AIModel" > "hasMetaData" > "Literal" and I add all meta info as a JSON.

**Comment by dcorsar** [comment]
'hasMetaData' is a bit generic as a lot of the annotation properties are meta data; is it just case structure meta-data that's being stored? if so, how about something like 'hasCaseStructureMetaData' ?

**Comment by anjanaw** [comment]
I'd like that!

**Comment by dcorsar** [comment]
Apologies for the delay; have added it as a datatype property to aimodel.rdf in main branch. I've added a restriction to AI Model class for it.  It may have been better to have defined i as an annotation property, but if we want to have the restriction it'll need to be a datatype. Either way, its there and can be used for what we need at the moment, and can change to a annotation property in future if feel that's more appropriate.
