### ISSUE TITLE
Remove use case individuals from explanationexperience.rdf

### ISSUE THREAD

**Issue by dcorsar** [isee4xai/iSeeOnto#4]
Refactor explanationexperience.rdf to be the ontology for describing explanation experiences, and move the use case individuals into their own rdf file which imports explanationexperience.rdf

**Comment by dcorsar** [comment]
Update [https://github.com/isee4xai/iSeeOnto/commit/610948b047fdb8f197d801e2320aa46a81610328]

Created [https://github.com/isee4xai/iSeeOnto/blob/main/BoschExplanationExperience.owl] for Bosch explanation experience from explainationexperience.rdf

**Comment by martcaro** [comment]
Properties from ExplainabilityTechnique are not loaded into BoschExplanationExperience.owl, so the properties related to BoschAnomalyVisualisation instance are missing.
