### ISSUE TITLE
userevalutaton deleted concepts

### ISSUE THREAD

**Issue by dcorsar** [isee4xai/iSeeOnto#40]
Just checking the userevaluation.rdf and it has the concepts 'Steps' and 'UserEvaluationResult'.
I'm pretty sure we decided to delete these as we're using alternatives 'Response Options Sequence' and 'UserEvaluationResponse'. 

It could be a git issue with uploading / merging - @ike01  and @anjanaw  can you please confirm we're not using these and I'll get them deleted?

**Comment by ike01** [comment]
Yes, we don't use those classes. Should be fine to delete them

**Comment by chamathpali** [comment]
@ike01 @dcorsar im trying to address an issue with the case structure export for eval questions,  Can i know if there are mapping for these options?

![image](https://user-images.githubusercontent.com/5123109/233429267-954e9175-343b-4f85-9554-21e1e8e11093.png)

**Comment by anjanaw** [comment]
we have these:
Free-Text: http://www.w3id.org/iSeeOnto/userevaluation#Open_Question
Radio: http://www.w3id.org/iSeeOnto/userevaluation#SingleChoiceNominalQuestion
Checkbox: http://www.w3id.org/iSeeOnto/userevaluation#MultipleChoiceNominalQuestion
Likert: http://www.w3id.org/iSeeOnto/userevaluation#Likert_Scale_Question

We need concept for _**Number**_

**Comment by ike01** [comment]
@chamathpali @anjanaw please what do you refer to as a Number question? Do you mean the question or the response type as they are separate entities? Maybe we add subclasses to Open_Question class to specify Free-Text open questions and Numeric open questions?

**Comment by anjanaw** [comment]
response type is a number, like the others in my previous comment. sub-classes will be good.

**Comment by ike01** [comment]
Have added Number Question as subclass of Open Question in the PR

**Comment by anjanaw** [comment]
Number Question needs some attributes to store min and max values to indicate a valid range

**Comment by anjanaw** [comment]
![Screenshot 2023-05-15 at 09 20 53](https://github.com/isee4xai/iSeeOnto/assets/233262/429d17ee-a97f-4c42-93c8-3bc525c5e23b)
I have added this to the case structure, once its created on iSeeOnto please close the issue
