### ISSUE TITLE
Knowledge level 

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeOnto#42]
On Cockpit, it would be nicer if there was a way to sort these values. 

![Screenshot 2022-12-09 at 19 54 08](https://user-images.githubusercontent.com/233262/206785904-ec93e44a-fdfb-4a45-923d-701341f0d93b.png)

**Comment by chamathpali** [comment]
If the labels can have an index like 
```
0 - No Knowledge
1 - Novice  ...
```
I can sort it in the cockpit

**Comment by ike01** [comment]
@dcorsar can we use the `sequence index` like we have for `Question`?

**Comment by dcorsar** [comment]
Yes - we can update the textual definition of sequence index to be more
general, and then we can use it for the knowledge level as well.
