### ISSUE TITLE
Updates to Behaviour Tree RDF

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeOnto#43]
We need to add a few new nodes to the ontology from D3.3.

**Comment by dcorsar** [comment]
Is it just those in Table 1 of the deliverable?

**Comment by anjanaw** [comment]
yes please!, also current rdf might have nodes we need to remove.

**Comment by dcorsar** [comment]
ok, I've added the nodes types in the [d3_3-bt-nodes branch](https://github.com/isee4xai/iSeeOnto/tree/d3_3-bt-nodes).
Couple of points to discuss:

- The definitions in D3.3 indicate two or more children; for example Varient is referred to as a type of "sequence node with two or more children" but the definition states "Right sibling(s) generate explanations that clarify explanations generated by the left sibling(s)". So do should instances of Varient nodes be limited to only two children, or is it the case that the definition should be more general like "sibling at index n+1 generates explanations that clarify explanations generated by the sibling at index n".
- The custom node is reffered to as either a Sequence or Priority node. If we define a single `Custom node` class as a subclass of `Sequence Node` and `Priority Node` then any instance of `Custom node` will also be an instance of `Sequence Node` and `Priority Node`. To avoid this, are we happy to defined a `Custom Sequence Node` class that is a subclass of `Sequence Node` and a `Custom Priority Node` class that is a subclass of `Priority Node` (we may also want to explicitly state that `Sequence Node` `is distinct from` `Priority Node` but thats a different question).

**Comment by anjanaw** [comment]
From the meeting, conclusions were, 
1.  a parent can have more than 2 children and this "sibling at index n+1 generates explanations that clarify explanations generated by the sibling at index n"
2. For now, we will not use custom nodes. 
3. Please add a new "User Question" Node of type Action Node.
