### ISSUE TITLE
add version attribute to Explanation Experience concept

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeOnto#48]
we need to record the version of a case in the case structure. 
Example: 
![Screenshot 2023-05-03 at 11 59 53](https://user-images.githubusercontent.com/233262/235898168-77391ae0-b26b-4b3f-9163-53e7074d4bb7.png)

**Comment by ike01** [comment]
Just like the comment detail, that could be added as an annotation using owl:versionInfo when creating an instance.

**Comment by anjanaw** [comment]
<img width="1440" alt="Screenshot 2023-05-04 at 10 11 18" src="https://user-images.githubusercontent.com/233262/236161000-d1bc34f4-6289-472d-9409-f61e97d2df27.png">
Should it not be added here like comment?

**Comment by ike01** [comment]
No, don't think we need that unless we want to add a version number to the class as well
