### ISSUE TITLE
User's type of knowledge

### ISSUE THREAD

**Issue by dcorsar** [isee4xai/iSeeOnto#5]
In the User module, where to define the types of knowledge that a user has. 

The Explanation Ontology defines the Knowledge class, as a subclass of DOL#Theory. There are several subclasss of Knowledge defined by the Explanation Ontology (contextual knowledge, Experiential knowledge, etc). For the user module, we wish to represent domain knowledge and knowledge of AI methods, where should these be situated in the hierarchy?

**Comment by anjanaw** [comment]
added none, novice, advanced beginner, competent, proficient, and expert for both AI Method Knowledge and Domain Knowledge.

**Comment by anjanaw** [comment]
What we have now is `User` `hasKnowledge` `AIMethodKnowledge` `hasLevel` `High`
We want `User` `quntifiedKnoweldgeOf` `KnowledgeOf` [`hasLevel` `Expert`] and [`subject` `Thing` (`Domain` or `AI Method`)]

**Comment by dcorsar** [comment]
> added none, novice, advanced beginner, competent, proficient, and expert for both AI Method Knowledge and Domain Knowledge.

There have been added as individuals of type `KnowledgeLevel` and so can be used for any concept (AI Method, Domain, etc)
