### ISSUE TITLE
Metadata for explainers

### ISSUE THREAD

**Issue by martcaro** [isee4xai/iSeeOnto#50]
Metadata for exaplainers are required to do the filtering step properly. The metada we should include is the following:
- modelAccess: Object property. Description: if the explainer execution is made by file or url. Values: Any, File, URL
- supportsBWImage: New DatasetType instance (in explainer.owl). Description: only for images, if supports RAW images.	
- needsTrainingData: Object property. Description: if the explainer needs training data, the user has to upload it. Values: True-False

More details about how to use these properties (and other ones already in the ontology) here: https://docs.google.com/spreadsheets/d/1v8d89Ex_Fm_4JOiAmagaawQA1UppfVMKwKgVGm-Wnf8/edit#gid=1337559317

**Comment by dcorsar** [comment]
Looks good.
Are model access and needsTrainingData object properties or would it be
better to have them as data type properties with ranges xsd:anyURI and
xsd:Boolean?

**Comment by ike01** [comment]
Model access type can be non-URI.
 
How about - Explainer ‘has model access’ ModelAccessType. 
And ModelAccessType has individuals: Any, File and URL

**Comment by martcaro** [comment]
@dcorsar I guess it's better to have has model access and needsTrainingData as object properties, because they are going to appear always, right? Data property is a good option, though.

@ike01 I agree

**Comment by dcorsar** [comment]
Yes, this looks like a good option to model that requirement. Will we also
be capturing the URL and/or the location/name of the file or is it just
that the model is accessed through a File or URL?

**Comment by dcorsar** [comment]
What would the value of needsTrainingData be if its an ObjectProperty? Will
it be pointing to details of the training data?

**Comment by martcaro** [comment]
Regarding modelAccess: we only need to capture if the model is uploaded by file or shared by URL, no need of adding more information.
Regarding needsTrainingData: we are going to represent that property with True or False, so and idea could be to create a class TrainingDataRequirement, with two instances TrainingDataRequired (True), and NoTrainingDataRequired (False). Let me know if you think this is good, or we might look for another idea!

**Comment by ike01** [comment]
It's probably best to use data properties since it's ever going to be either true or false strings. 
We could go with 'needs training data' with xsd:string data type and include {"True", "False"} for the data range. Thoughts?




    <owl:DatatypeProperty rdf:about="http://www.w3id.org/iSeeOnto/explainer#needs_training_data">
        <rdfs:range>
            <rdfs:Datatype>
                <owl:oneOf>
                    <rdf:Description>
                        <rdf:type rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#List"/>
                        <rdf:first>False</rdf:first>
                        <rdf:rest>
                            <rdf:Description>
                                <rdf:type rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#List"/>
                                <rdf:first>True</rdf:first>
                                <rdf:rest rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"/>
                            </rdf:Description>
                        </rdf:rest>
                    </rdf:Description>
                </owl:oneOf>
            </rdfs:Datatype>
        </rdfs:range>
        <rdfs:label xml:lang="en">needs training data</rdfs:label>
    </owl:DatatypeProperty>

**Comment by martcaro** [comment]
Okay, yes, maybe it is better option to use data property, TrainingDataRequirement might be a very specific class. If we use data property, I think we could use xsd:boolean instead of string???
