### ISSUE TITLE
Explanation Modality subclasses

### ISSUE THREAD

**Issue by dcorsar** [isee4xai/iSeeOnto#7]
Presently Explanation Modaility does not have any subclasses, should we define subclasses for common modalities, such as image, text, etc. in the explainer.rdf ontology?

**Comment by anjanaw** [comment]
:)

**Comment by dcorsar** [comment]
Suggestion: we make use of the sio:media class - this contains various subclasses for audio recording, file, figure, etc. 
Then we define 
TechnicalFacility canPresent sio:media
and ExplanationModality presentedAs sio:media
